FROM node:19.4-bullseye AS dev

WORKDIR /usr/src/app

COPY package*.json ./

RUN --mount=type=cache,target=/usr/src/app/.npm \
  npm set cache /usr/src/app/.npm && \
  npm install --prefer-offline

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]
