version: '3.9'

services:
  db-dev:
    container_name: db-dev
    image: mysql:8.0
    env_file:
      - .env
    networks:
      - dataannotation-logs-app
    volumes:
      - db-dev-data:/var/lib/mysql
    ports:
      - 3306:3306
    profiles:
      - dev

  db-prod:
    container_name: db-prod
    image: mysql:8.0
    env_file:
      - .env
    networks:
      - dataannotation-logs-app
    volumes:
      - db-prod-data:/var/lib/mysql
    profiles:
      - prod

  api-dev:
    container_name: api-dev
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    depends_on:
      - db-dev
    env_file:
      - .env
    environment:
      DATASOURCE_URL: jdbc:mysql://db-dev:3306/${MYSQL_DATABASE}
      DATASOURCE_USER: ${MYSQL_USER}
      DATASOURCE_PASS: ${MYSQL_PASSWORD}
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    networks:
      - dataannotation-logs-app
    volumes:
      - type: bind
        source: ./api
        target: /app
    profiles:
      - dev

  api-prod:
    container_name: api-prod
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    depends_on:
      - db-prod
    env_file:
      - .env
    environment:
      DATASOURCE_URL: jdbc:mysql://db-prod:3306/${MYSQL_DATABASE}
      DATASOURCE_USER: ${MYSQL_USER}
      DATASOURCE_PASS: ${MYSQL_PASSWORD}
    ports:
      - 8080:8080
    networks:
      - dataannotation-logs-app
    profiles:
      - prod

  client-dev:
    container_name: client-dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - VITE_API_BASE_URL=http://api-dev:8080/api
    depends_on:
      - api-dev
    ports:
      - '5173:5173'
    networks:
      - dataannotation-logs-app
    volumes:
      - type: bind
        source: ./client
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/node_modules
    profiles:
      - dev

  client-prod:
    container_name: client-prod
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    environment:
      - VITE_API_BASE_URL=http://api-prod:8080/api
    depends_on:
      - api-prod
    ports:
      - '80:80'
    networks:
      - dataannotation-logs-app
    profiles:
      - prod

networks:
  dataannotation-logs-app:
    name: dataannotation-logs-app

volumes:
  db-dev-data:
  db-prod-data:
